name       : elementary-icon-theme
version    : '5.0'
release    : 10
source     :
    - https://github.com/elementary/icons/archive/5.0.tar.gz : 7ef504b8766855e66dfac0fc09135433131cacfdb58bad142151943cf39f6313
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : An icon theme designed to be smooth, sexy, clear, and efficient.
description: |
    An icon theme designed to be smooth, sexy, clear, and efficient.
setup      : |
    %meson_configure -Dvolume_icons=false
build      : |
    %ninja_build
install    : |
    %ninja_install
