name       : elementary-icon-theme
version    : 5.2.0
release    : 15
source     :
    - https://github.com/elementary/icons/archive/5.2.0.tar.gz : b4a2b2205443dbfaecd42f0594bdf9c95d9787781b6fe1250ffa2c216a68ec7c
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Icons from the Elementary Project
description: |
    Icons from the Elementary Project. An icon theme designed to be smooth, sexy, clear, and efficient.
builddeps  :
    - inkscape
    - xcursorgen
setup      : |
    %meson_configure -Dvolume_icons=false
build      : |
    %ninja_build
install    : |
    %ninja_install
