name        : elementary-icon-theme
version     : 3.2.1
release     : 6
source     :
    - https://launchpad.net/elementaryicons/3.x/3.2.1/+download/elementary-icon-theme-3.2.1.tgz : 3877a80c1428da9e6a3c97327ad17510271f729a2d7c162f13aafca225a1672f
license     : GPL-2.0+
summary     : An icon theme designed to be smooth, sexy, clear, and efficient.
description : |
    An icon theme designed to be smooth, sexy, clear, and efficient.
setup      : |
build      : |
install    : |
    mkdir -p %installroot%/usr/share/icons/elementary/
    mkdir -p %installroot%/usr/share/doc/elementary-icon-theme/
    mv AUTHORS %installroot%/usr/share/doc/elementary-icon-theme/
    mv CONTRIBUTORS %installroot%/usr/share/doc/elementary-icon-theme/
    mv COPYING %installroot%/usr/share/doc/elementary-icon-theme/
    mv * %installroot%/usr/share/icons/elementary/
