name       : elementary-icon-theme
version    : 5.0.4
release    : 13
source     :
    - https://github.com/elementary/icons/archive/5.0.4.tar.gz : 48f0ccb3796bfe2d02acab972ddbdd240c97b09f4b0e914aa1f49a453f86d1a0
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : An icon theme designed to be smooth, sexy, clear, and efficient.
description: |
    An icon theme designed to be smooth, sexy, clear, and efficient.
setup      : |
    %meson_configure -Dvolume_icons=false
build      : |
    %ninja_build
install    : |
    %ninja_install
