name       : elementary-icon-theme
version    : 5.0.2
release    : 11
source     :
    - https://github.com/elementary/icons/archive/5.0.2.tar.gz : 1749545bd45f79493e0546201b1a7b6199f0d679bb8c85fae6a4f57c57977ad0
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : An icon theme designed to be smooth, sexy, clear, and efficient.
description: |
    An icon theme designed to be smooth, sexy, clear, and efficient.
setup      : |
    %meson_configure -Dvolume_icons=false
build      : |
    %ninja_build
install    : |
    %ninja_install
